; tox is just used for testing the python/django matrix locally
[tox]
envlist =
    py{311}-django{41,42,50,51,52}-{postgresql,sqlite}
    py{312}-django{42,50,51,52,60,61}-{postgresql,sqlite}
    py{313}-django{51,52,60,61}-{postgresql,sqlite}
    py{314}-django{52,60,61}-{postgresql,sqlite}
    py{311,312,313,314}-flake8

[testenv]
passenv =
    postgresql: POSTGRES_USER POSTGRES_PASSWORD
setenv =
    PYTHONPATH = {toxinidir}
deps =
    django41: Django>=4.1,<4.2
    django42: Django>=4.2,<4.3
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    django61: Django>=6.1,<6.2
dependency_groups =
    test
commands =
    python --version
    pip list
    coverage run -m pytest -v
    coverage report

[testenv:py{311,312,313,314}-flake8]
skip_install = True
dependency_groups =
    lint
commands =
    python --version
    pip list
    flake8 -v src tests docs
