name: "Lint"

on:
  push:
    branches: [ develop ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]
  schedule:
    - cron: '30 22 15 * *'

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.10'

      - name: Install flake8
        run: |
          pip install --group lint
          pip list

      - name: Run flake8
        run: flake8 -v src tests docs

  bandit:
    name: bandit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.10'

    - name: Install bandit
      run: |
        pip install --group security
        pip list

    - name: Run bandit
      # "B101:assert_used" is allowed in tests.
      run: |
        bandit -r src docs
        bandit -r tests --skip B101
